apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api-dep
  namespace: dev-smart-accounting-services
spec:
  selector:
    matchLabels:
      app: notification-api
  replicas: 3 # tells deployment to run 2 pods matching the template
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: notification-api
        aadpodidbinding: "aks-pods-identity"
    spec:
      containers:
      - name: notification-api-container
        image: acrsmartaccounting.azurecr.io/notificationapi:latest
        imagePullPolicy: Always
        env:
          - name: AzureSignalRConfig__ConnectionString
            valueFrom:
             secretKeyRef:
               name: signalr-connection-string
               key: signalr-connection-string
          - name: ApplicationInsightsConfig__InstrumentationKey
            valueFrom:
             secretKeyRef:
               name: application-insights-key
               key: application-insights-key
          - name: SqlDbConfig__ConnectionString
            valueFrom:
             secretKeyRef:
               name: sql-db-connection-string
               key: sql-db-connection-string
          - name: ServiceBusConfig__ListenAndSendConnectionString
            valueFrom:
             secretKeyRef:
               name: service-bus-connection-string
               key: service-bus-connection-string
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/mnt/secrets-store"
            name: secrets-store-inline
            readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "kv-smart-accounting"

---

apiVersion: v1 
kind: Service 
metadata: 
  name:  notification-api-svc
  namespace: dev-smart-accounting-services
spec: 
  type: ClusterIP
  selector: 
    app:  notification-api
  ports: 
  - name: https 
    port: 443
    targetPort: 80