apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-smart-accounting
  namespace: dev-smart-accounting-services
spec:
  provider: azure
  secretObjects:                                
  - secretName: signalr-connection-string
    type: Opaque
    data: 
    - objectName: signalr-connection-string                    
      key: signalr-connection-string

  - secretName: form-recognizer-key
    type: Opaque
    data: 
    - objectName: form-recognizer-key                   
      key: form-recognizer-key

  - secretName: service-bus-connection-string
    type: Opaque
    data: 
    - objectName: service-bus-connection-string                    
      key: service-bus-connection-string

  - secretName: storage-account-connection-string
    type: Opaque
    data: 
    - objectName: storage-account-connection-string                    
      key: storage-account-connection-string

  - secretName: storage-account-key
    type: Opaque
    data: 
    - objectName: storage-account-key                   
      key: storage-account-key

  - secretName: sql-db-connection-string
    type: Opaque
    data: 
    - objectName: sql-db-connection-string                     
      key: sql-db-connection-string

  - secretName: cosmos-db-connection-string
    type: Opaque
    data: 
    - objectName: cosmos-db-connection-string                    
      key: cosmos-db-connection-string

  - secretName: application-insights-key
    type: Opaque
    data: 
    - objectName: application-insights-key         
      key: application-insights-key
  parameters:
    usePodIdentity: "true"                                            
    keyvaultName: "kv-smart-accounting"                                        
    objects:  |
      array:
        - |
          objectName: signalr-connection-string                                                                
          objectType: secret                                               
          objectVersion: ""                                                
        - |
          objectName: form-recognizer-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: service-bus-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: storage-account-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: storage-account-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: sql-db-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: cosmos-db-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: application-insights-key
          objectType: secret
          objectVersion: ""

    tenantId: ""       # [REQUIRED] the tenant ID of the key vault