version: '3.4'

services:
  documentanalyzer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  fileprocessor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  notification.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  processeddocument.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

